<template>
  <div class="main-pricing">
    <AnimatedCustom />
    <section class="section">
      <div class="animate__fadeIn animate__animated top-navbar">
        <nuxt-link to="/"
          ><img
            src="@/assets/images/main/go_back.svg"
            alt="go back"
            class="go_back cursor-pointer"
        /></nuxt-link>
        <img
          class="cursor-pointer menu-btn"
          data-nav="_3dScaleRotate"
          src="@/assets/images/main/menu.svg"
          alt="menu"
        />
      </div>
      <div class="header">
        <div class="animate__fadeIn animate__animated">
          <p class="header-name my-3">
            <span
              v-for="(char, index) in pricing1"
              class="pricing-title"
              :key="index"
              >{{ char }}</span
            >
          </p>
          <p class="header-marketing my-6">
            <span
              v-for="(char, index) in pricing2"
              class="pricing-subtitle"
              :key="index"
              >{{ char }}</span
            >
          </p>
          <p class="header-info mt-2 second-subtitle">
            Natex is planning its first ever sale of NFTs (see Roadmap),
            conferring users platform usage rights and discounted fares for
            riders, zero commission rides for drivers, and a share of the income
            generated by the platform to all NFT owners.
          </p>
        </div>
        <main>
          <div class="content-wrapper">
            <div class="left w-[29%] flex p-10 align-middle items-center">
              <img
                src="@/assets/images/check/vega.svg"
                alt="vega image"
                class="mr-2"
              />
              <span>Vega NFT</span>
            </div>

            <div class="right text-center p-10 flex justify-center w-[70%]">
              <p>3% of individual driver income</p>
            </div>
          </div>
          <div class="content-wrapper">
            <div class="left w-[29%] flex p-10 align-middle items-center">
              <img
                src="@/assets/images/check/centaurus.svg"
                alt="vega image"
                class="mr-2"
              />
              <span>Centaurus NFT</span>
            </div>

            <div class="right text-center p-10 flex justify-center w-[70%]">
              <p>3% of income of 3 drivers</p>
            </div>
          </div>
          <div class="content-wrapper">
            <div class="left w-[29%] flex p-10 align-middle items-center">
              <img
                src="@/assets/images/check/sirius.svg"
                alt="sirius image"
                class="mr-2"
              />
              <span>Sirius NFT</span>
            </div>

            <div class="right text-center p-10 flex justify-center w-[70%]">
              <p>3% of individual 6 drivers</p>
            </div>
          </div>
          <div class="content-wrapper">
            <div class="left w-[29%] flex p-10 align-middle items-center">
              <img
                src="@/assets/images/check/archangel.svg"
                alt="archangel image"
                class="mr-2"
              />
              <span>Archangel NFT</span>
            </div>

            <div class="right text-center p-10 flex justify-center w-[70%]">
              <p>3% of income of 12 driver</p>
            </div>
          </div>
        </main>
      </div>
    </section>
  </div>
</template>

<script>
import { gsap } from "gsap";
export default {
  data() {
    return {
      pricing1: "PRICING".split(""),
      pricing2: "Become a Natex NFT owner and earn unparallaled rewards.".split(
        ""
      ),
    };
  },
  async mounted() {
    await this.$store.dispatch("handleSidebarMenu");
    gsap.from(".pricing-title", {
      y: "100%",
      opacity: 0,
      duration: 2,
      stagger: 0.1,
      ease: "power2.out",
    });
    gsap.from(".pricing-subtitle", {
      y: "100%",
      opacity: 0,
      delay: 1,
      duration: 1.8,
      stagger: 0.1,
      ease: "power1.out",
    });
    gsap.from(".second-subtitle", {
      y: -100,
      autoAlpha: 0,
      duration: 1.5,
      delay: 1.2,
    });
    
    gsap.fromTo(
      ".content-wrapper",
      {
        autoAlpha:0,
        scale: 0.8,
      },
      {
        scale: 1,
        autoAlpha:1,
        duration: 1,
        delay:1.5,
        stagger: 0.3,
      }
    );
  },
};
</script>

<style scoped>
.main-pricing {
  background-image: url("@/assets/images/main/bg.svg");
  background-size: cover;
  min-height: 100vh;
}
.section {
  min-height: 100vh;

  width: 80%;
  margin: 0 auto;
  display: flex;
  flex-direction: column;
  justify-content: center;
}

.top-navbar {
  margin: 20px auto;
  justify-self: center;
  width: 100%;
  display: flex;
  justify-content: space-between;
  justify-self: end;
}

.header {
  flex-grow: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}

.header-name {
  font-family: "Feature Mono";
  text-align: center;
  font-family: monospace;
  letter-spacing: 2px;
  font-style: normal;
  font-weight: 400;
  font-size: 20px;
  line-height: 24px;
  background: linear-gradient(180deg, #00d1ff 0%, #64fd93 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}

.header-marketing {
  font-family: "Feature Mono";
  text-align: center;
  font-size: 24px;
  width: 90%;
  font-family: monospace;
}

.header-info {
  font-family: "Montserrat";
  width: 70%;
  margin: 0% auto;
  text-align: center;
  font-size: 14px;
  background: linear-gradient(
    180deg,
    #ffffff 0%,
    rgba(255, 255, 255, 0.45) 100%
  );
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}

main {
  width: 70%;
  margin-top: 15px;
}

.content-wrapper {
  display: flex;
  justify-content: space-between;
  /* transition: 0.3s all ease; */
}
.content-wrapper:hover .left,
.content-wrapper:hover .right {
  border-image: linear-gradient(
      264.81deg,
      rgba(0, 209, 255, 0.56) 6.82%,
      #62fc97 91.66%
    )
    1 1;
}

.left,
.right {
  transition: 0.3s all ease;
  background: rgba(255, 255, 255, 0.05);
  border: 1px solid rgba(255, 255, 255, 0.04);
  backdrop-filter: blur(10px);
}
.left {
  width: 29%;
  display: flex;
  padding: 10px;
  align-items: center;
}

.left span {
  font-family: "Montserrat";
}
.right p {
  font-family: "Montserrat";
}

.right {
  width: 70%;
  text-align: center;
  display: flex;
  justify-content: center;
}

@media (max-width: 992px) {
  main {
    width: 100%;
  }
}

@media (max-width: 768px) {
  .header-info {
    width: 90%;
  }
  .content-wrapper {
    flex-direction: column;
  }
  .left,
  .right {
    width: 100%;
    justify-content: center;
  }
  .right {
    margin-bottom: 8px;
  }
}

@media (max-width: 576px) {
  .section {
    width: 90%;
  }

  .header-marketing {
    font-size: 17px;
  }
}


@media screen and (max-width:400px) {
   
}
</style>
